<?php
namespace fairmeet\controller;
use PDO;
use PDOException;

require_once ('DB.php');
require_once ('../model/Meet.php');
require_once ('../model/Response.php');

try {
    $writeDB = DB::connectWriteDB();
    $readDB = DB::connectReadDB();

} catch (PDOException $e){
    error_log("Connection error - ".$e, 0);
    $response = new Response();
    $response->setHttpStatusCode(500);
    $response->setSuccess(false);
    $response->addMessage("Database Connection Error");
    $response->send();
    exit();
}

/** Authorization script goes here */

/** if we have a meeting id
 *
 *  example route: /meet/1009
 *
 */
if(array_key_exists("meetid", $_GET)){
    $meetid = $_GET['meetid'];

    //validate not blank, is numeric
    if($meetid == '' || !is_numeric($meetid)){
        $response = new Response();
        $response->setHttpStatusCode(400); //Bad Request
        $response->setSuccess(false);
        $response->addMessage("Meet Id cannot be blank or must be numeric");
        $response->send();
        exit();
    }
}

    /** GET request
     *
     *  Get the details of a meet
     * -- must be one of the attendees to do this
     *
     */
    if($_SERVER['REQUEST_METHOD'] === 'GET'){




    /** DELETE request
     *
     *  Delete a meet
     *  -- must be the organiser in order to do this
     *
     */
    } elseif ($_SERVER['REQUEST_METHOD'] === 'DELETE') {

        /** PATCH request
         *
         *  Update a meets details
         *  -- must be the organiser to do this
         *  -- use this to add attendee to a meet ??
         *  -- use this to remove an attendee??
         *
         */
    } elseif ($_SERVER['REQUEST_METHOD'] === 'PATCH') {

        /** POST request
         *
         * Can't POST to a specific meetID as these
         * will be generated by the system
         *
         */
    } else {
        $response = new Response();
        $response->setHttpStatusCode("405"); //method not allowed.
        $response->setSuccess(false);
        $response->addMessage("Request Message Not Allowed");
        $response->send();
        exit();
    }

/** show all finalised or unfinalised meets
 *
 *  maybe in v2
 *
 */

/** pagination
 *
 * maybe in v2
 *
 */


/** if no meetid provided
 *
 *  route: /meet
 *
 */

    /** GET request
     *
     */

    /** POST request
     *
     *  - create a new meet
     *
     */

/** endpoint not found  */

